spring.application.name=queueing-webapp
spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG

app.admin.clear-key=${APP_ADMIN_CLEAR_KEY:CLEAR-2026-MAXI}
app.admin.reset-key=${APP_ADMIN_RESET_KEY:RESET-2026-MAXI}